### PR TITLE
Fix extension caching

### PR DESCRIPTION
**Pull request by jbourassa**
See https://github.com/oxidize-rb/actions/pull/12#discussion_r1070711066

I tried it on wasmtime-rb and it worked, caches were restored for a faster build 🎉.

### CODE REVIEW

**Comment by ianks** [comment]
Great find, ty! I’ll cut a release for this when I get home.

**Review by ianks — APPROVED** [review]

**Comment by ianks** [comment]
released https://github.com/oxidize-rb/actions/releases/tag/v1.0.3

**Comment by jbourassa** [comment]
Thanks you @ianks 🙇

**Comment by ianks** [comment]
Also noticed an issue causing unnecessary re-compilation, fixed here https://github.com/oxidize-rb/rb-sys/commit/7f7fd2457c10905cf7e121358d2f992cc2330493

**Pull request merged**
